package reqql

import (
	"context"

	"github.com/doug-martin/goqu/v9"
	"github.com/doug-martin/goqu/v9/exp"
	"github.com/pkg/errors"
)

type QueryFuncArgs = func(ctx context.Context, dest any, query string, args ...any) error
type QueryFuncArg = func(ctx context.Context, dest any, query string, arg any) error

type QueryFunc interface{ QueryFuncArgs | QueryFuncArg }

type NoInputType = any
type QueryFuncType[T any] func(*T) (*goqu.SelectDataset, error)
type WhereFuncType[T any] func(*T) goqu.Expression
type OrderFuncType[T any] func(*T) exp.OrderedExpression
type LimitFuncType[T any] func(*T) any // Should return uint or nil
type OffsetFuncType[T any] func(*T) uint

func DefaultQueryParser[T any](_ *T) (*goqu.SelectDataset, error) {
	// Equivalent to SELECT * FROM (VALUES (1, 'V1'), (2, 'V2')) AS data (id, value)
	// goqu doesn't have a direct VALUES helper that matches exactly the original string-based default,
	// so we'll use a simple SELECT from a table named 'data' as a placeholder if needed,
	// or just a basic from.
	return goqu.From("data").Select("id", "value"), nil
}

func WhereTrueFunc[T any](_ *T) goqu.Expression {
	return nil // goqu.Where(nil) is a no-op
}

func NoOrderFunc[T any](_ *T) exp.OrderedExpression {
	return nil
}

func NoLimitFunc[T any](_ *T) any {
	return nil
}

func NoOffsetFunc[T any](_ *T) uint {
	return 0
}

// Processor is the queryer processor useful to proceed the
// queryer with always the same querying function.
type Processor[InputType any, QueryFuncType QueryFunc] struct {
	queryer   *Queryer[InputType]
	queryFunc QueryFuncType
}

// Proceed is like [Proceed] but with the pre-configured queryer and query function.
func (p *Processor[InputType, QueryFuncType]) Proceed(ctx context.Context, input *InputType, dest any) error {
	return Proceed(ctx, p.queryer, input, dest, p.queryFunc)
}

// NewProcessor build a queryer processor in order to execute the
// generated sql query with always the same querying function.
func NewProcessor[InputType any, QueryFuncType QueryFunc](q *Queryer[InputType], f QueryFuncType) *Processor[InputType, QueryFuncType] {
	p := new(Processor[InputType, QueryFuncType])
	p.queryer = q
	p.queryFunc = f

	return p
}

type Filter[InputType any] struct {
	whereFunc  WhereFuncType[InputType]
	orderFunc  OrderFuncType[InputType]
	limitFunc  LimitFuncType[InputType]
	offsetFunc OffsetFuncType[InputType]
}

type Queryer[InputType any] struct {
	queryFunc QueryFuncType[InputType]
	Filter[InputType]
	arg any
}

// WithQueryParserFunc set the function that provides the base dataset (SELECT ... FROM ...).
func (q *Queryer[InputType]) WithQueryParserFunc(f QueryFuncType[InputType]) *Queryer[InputType] {
	q.queryFunc = f
	return q
}

// WithWhereFunc sets the function that provides the "where" expressions.
func (q *Queryer[InputType]) WithWhereFunc(f WhereFuncType[InputType]) *Queryer[InputType] {
	q.whereFunc = f
	return q
}

// WithOrderFunc sets the function that provides the "order" expressions.
func (q *Queryer[InputType]) WithOrderFunc(f OrderFuncType[InputType]) *Queryer[InputType] {
	q.orderFunc = f
	return q
}

// WithLimitFunc sets the function that provides the "limit".
func (q *Queryer[InputType]) WithLimitFunc(f LimitFuncType[InputType]) *Queryer[InputType] {
	q.limitFunc = f
	return q
}

// WithOffsetFunc sets the function that provides the "offset".
func (q *Queryer[InputType]) WithOffsetFunc(f OffsetFuncType[InputType]) *Queryer[InputType] {
	q.offsetFunc = f
	return q
}

// SetArg is kept for backward compatibility but goqu handles args natively.
// If set, it will be used when Proceed is called with QueryFuncArg.
func (q *Queryer[InputType]) SetArg(arg any) *Queryer[InputType] {
	q.arg = arg
	return q
}

// Parse returns the SQL generated by the queryer and its arguments.
func (q *Queryer[InputType]) Parse(input *InputType) (sql string, args []any, err error) {
	ds, err := q.queryFunc(input)
	if err != nil {
		return "", nil, err
	}

	if w := q.whereFunc(input); w != nil {
		ds = ds.Where(w)
	}

	if o := q.orderFunc(input); o != nil {
		ds = ds.Order(o)
	}

	if l := q.limitFunc(input); l != nil {
		if limit, ok := l.(uint); ok {
			ds = ds.Limit(limit)
		}
	}

	if offset := q.offsetFunc(input); offset > 0 {
		ds = ds.Offset(offset)
	}

	return ds.ToSQL()
}

// Proceed executes the queryer using specialized query functions.
func Proceed[InputType any, QF QueryFunc](
	ctx context.Context, q *Queryer[InputType],
	input *InputType, dest any, queryFunc QF) error {
	sql, args, err := q.Parse(input)
	if err != nil {
		return err
	}

	switch f := any(queryFunc).(type) {
	case QueryFuncArg:
		// If q.arg is set, we prefer it for QueryFuncArg (backward compat)
		arg := any(args)
		if q.arg != nil {
			arg = q.arg
		}
		return f(ctx, dest, sql, arg)
	case QueryFuncArgs:
		return f(ctx, dest, sql, args...)
	}

	return errors.New("unpredictible error (wtf)")
}

func New[InputType any]() *Queryer[InputType] {
	q := Queryer[InputType]{}
	q.
		WithQueryParserFunc(DefaultQueryParser).
		WithWhereFunc(WhereTrueFunc).
		WithOrderFunc(NoOrderFunc).
		WithLimitFunc(NoLimitFunc).
		WithOffsetFunc(NoOffsetFunc)

	return &q
}
