package reqql

import (
	"context"
	"fmt"

	"github.com/pkg/errors"
)

type QueryFuncArgs = func(ctx context.Context, dest any, query string, args ...any) error
type QueryFuncArg = func(ctx context.Context, dest any, query string, arg any) error

type QueryFunc interface{ QueryFuncArgs | QueryFuncArg }

type NoInputType = any
type SelectFuncType[T any] func(*T) (string, error)
type QueryFuncType[T any] func(*T) (string, any, error)
type FromFuncType[T any] func(*T) (string, error)
type WhereFuncType[T any] func(*T) (string, error)
type OrderFuncType[T any] func(*T) (string, error)
type LimitFuncType[T any] func(*T) (string, error)
type OffsetFuncType[T any] func(*T) (int, error)

const (
	selectAll   = "*"
	fromDefault = "(VALUES (1, 'V1'), (2, 'V2')) AS data (id, value)"
	whereTrue   = "TRUE"
	noOrder     = "1"
	noLimit     = "ALL"
	noOffset    = 0
	queryFormat = `
SELECT %s
FROM %s`
	sqlFormat = `%s
WHERE %s
ORDER BY %s
LIMIT %s
OFFSET %d`
)

func DefaultQueryParser[T any](_ *T) (sql string, arg any, err error) {
	return fmt.Sprintf(queryFormat, selectAll, fromDefault), nil, nil
}

func WhereTrueFunc[T any](_ *T) (string, error) {
	return whereTrue, nil
}

func NoOrderFunc[T any](_ *T) (string, error) {
	return noOrder, nil
}

func NoLimitFunc[T any](_ *T) (string, error) {
	return noLimit, nil
}

func NoOffsetFunc[T any](_ *T) (int, error) {
	return noOffset, nil
}

// Processor is the queryer processor useful to proceed the
// queryer with always the same querying function.
type Processor[InputType any, QueryFuncType QueryFunc] struct {
	queryer   *Queryer[InputType]
	queryFunc QueryFuncType
}

// Proceed is like [Proceed] but with the pre-configured queryer and query function.
// See [NewProcessor].
func (p *Processor[InputType, QueryFuncType]) Proceed(ctx context.Context, input *InputType, dest any) error {
	return Proceed(ctx, p.queryer, input, dest, p.queryFunc)
}

// NewProcessor build a queryer processor in order to execute the
// generated sql query with always the same querying function.
func NewProcessor[InputType any, QueryFuncType QueryFunc](q *Queryer[InputType], f QueryFuncType) *Processor[InputType, QueryFuncType] {
	p := new(Processor[InputType, QueryFuncType])
	p.queryer = q
	p.queryFunc = f

	return p
}

type Filter[InputType any] struct {
	whereFunc  WhereFuncType[InputType]
	orderFunc  OrderFuncType[InputType]
	limitFunc  LimitFuncType[InputType]
	offsetFunc OffsetFuncType[InputType]
}

type Queryer[InputType any] struct {
	queryFunc QueryFuncType[InputType]
	Filter[InputType]
	arg any
}

// WithQueryParserFunc set the function that provides the "SELECT … FROM …" part of the queryer.
// WithQueryParserFunc WHERE WhereFunc(…) ORDER BY OrderFunc(…) LIMIT LimitFunc(…) OFFSET OrderFunc(…)
func (q *Queryer[InputType]) WithQueryParserFunc(f QueryFuncType[InputType]) *Queryer[InputType] {
	q.queryFunc = f

	return q
}

// WithWhereFunc (MUST BE SQL SAFE !) set the function that provide the "where" part of the queryer.
// SELECT SelectFunc(…) FROM FromFunc() WHERE WhereFunc(…) ORDER BY OrderFunc(…) LIMIT LimitFunc(…) OFFSET OrderFunc(…)
func (q *Queryer[InputType]) WithWhereFunc(f WhereFuncType[InputType]) *Queryer[InputType] {
	q.whereFunc = f

	return q
}

// WithOrderFunc (MUST BE SQL SAFE !) set the function that provide the "order" part of the queryer.
// SELECT SelectFunc(…) FROM FromFunc() WHERE WhereFunc(…) ORDER BY OrderFunc(…) LIMIT LimitFunc(…) OFFSET OrderFunc(…)
func (q *Queryer[InputType]) WithOrderFunc(f OrderFuncType[InputType]) *Queryer[InputType] {
	q.orderFunc = f

	return q
}

// WithLimitFunc (MUST BE SQL SAFE !) set the function that provide the "limit" part of the queryer.
// SELECT SelectFunc(…) FROM FromFunc() WHERE WhereFunc(…) ORDER BY OrderFunc(…) LIMIT LimitFunc(…) OFFSET OrderFunc(…)
func (q *Queryer[InputType]) WithLimitFunc(f LimitFuncType[InputType]) *Queryer[InputType] {
	q.limitFunc = f

	return q
}

// WithOffsetFunc (MUST BE SQL SAFE !) set the function that provide the "offset" part of the queryer.
// SELECT SelectFunc(…) FROM FromFunc() WHERE WhereFunc(…) ORDER BY OrderFunc(…) LIMIT LimitFunc(…) OFFSET OrderFunc(…)
func (q *Queryer[InputType]) WithOffsetFunc(f OffsetFuncType[InputType]) *Queryer[InputType] {
	q.offsetFunc = f

	return q
}

// SetArg set the arg wich will be forwarded to the chosen sql queryer
// function when querying if arg(s) is needed.
// arg can be sql unsafe.
func (q *Queryer[InputType]) SetArg(arg any) *Queryer[InputType] {
	q.arg = arg

	return q
}

// Parse return the SQL generated by the queryer
func (q *Queryer[InputType]) Parse(input *InputType) (sql string, arg any, err error) {
	query, arg, err := q.queryFunc(input)
	if err != nil {
		return "", arg, err
	}

	where, err := q.whereFunc(input)
	if err != nil {
		return "", arg, err
	}

	order, err := q.orderFunc(input)
	if err != nil {
		return "", arg, err
	}

	limit, err := q.limitFunc(input)
	if err != nil {
		return "", arg, err
	}

	offset, err := q.offsetFunc(input)
	if err != nil {
		return "", arg, err
	}

	sql = fmt.Sprintf(sqlFormat, query, where, order, limit, offset)

	return sql, arg, nil
}

// Proceed executes the queryer using specialized dao.QueryFunc like
// [dao.DBService.SelectContext], [dao..DBService.GetContext], [dao..DBService.NamedSelectContext] etc…
func Proceed[InputType any, QF QueryFunc](
	ctx context.Context, q *Queryer[InputType],
	input *InputType, dest any, queryFunc QF) error {
	sql, arg, err := q.Parse(input)
	if err != nil {
		return err
	}

	if arg != nil && q.arg != nil {
		data := map[string]any{
			"arg":   arg,
			"q.arg": q.arg,
		}

		return errors.New("Parse query function return not nil")
	}

	if q.arg != nil {
		arg = q.arg
	}

	switch f := any(queryFunc).(type) {
	case QueryFuncArg:
		return f(ctx, dest, sql, arg)
	case QueryFuncArgs:
		switch args := arg.(type) {
		case []any:
			return f(ctx, dest, sql, args...)
		case nil:
			return f(ctx, dest, sql)
		default:
			data := map[string]any{
				"function": fmt.Sprintf("%+v", queryFunc),
				"arg":      arg,
			}

			return errors.New(fmt.Sprintf("function need []any, %T given", args))
		}
	}

	return errors.New("unpredictible error (wtf)")
}

func New[InputType any]() *Queryer[InputType] {
	q := Queryer[InputType]{}
	q.
		WithQueryParserFunc(DefaultQueryParser).
		WithWhereFunc(WhereTrueFunc).
		WithOrderFunc(NoOrderFunc).
		WithLimitFunc(NoLimitFunc).
		WithOffsetFunc(NoOffsetFunc)

	return &q
}
