package reqql

import (
	"context"
	"fmt"

	"github.com/piprim/reqql/pkg/core"
	"github.com/pkg/errors"
)

type NoInputType = any
type SelectFuncType[T any] func(*T) (string, []any, error)
type QueryFuncType[T any] func(*T) (string, []any, error)
type FromFuncType[T any] func(*T) (string, []any, error)
type WhereFuncType[T any] func(*T) (string, []any, error)
type OrderFuncType[T any] func(*T) (string, []any, error)
type LimitFuncType[T any] func(*T) (string, []any, error)
type OffsetFuncType[T any] func(*T) (string, []any, error)

const (
	selectAll   = "*"
	fromDefault = "(VALUES (1, 'V1'), (2, 'V2')) AS data (id, value)"
	whereTrue   = "TRUE"
	noOrder     = "1"
	noLimit     = "ALL"
	noOffset    = "0"
	queryFormat = `
SELECT %s
FROM %s`
	sqlFormat = `%s
WHERE %s
ORDER BY %s
LIMIT %s
OFFSET %s`
)

func DefaultQueryParser[T any](_ *T) (sql string, args []any, err error) {
	return fmt.Sprintf(queryFormat, selectAll, fromDefault), nil, nil
}

func WhereTrueFunc[T any](_ *T) (string, []any, error) {
	return whereTrue, nil, nil
}

func NoOrderFunc[T any](_ *T) (string, []any, error) {
	return noOrder, nil, nil
}

func NoLimitFunc[T any](_ *T) (string, []any, error) {
	return noLimit, nil, nil
}

func NoOffsetFunc[T any](_ *T) (string, []any, error) {
	return noOffset, nil, nil
}

// Processor is the queryer processor useful to proceed the
// queryer with always the same querying function.
type Processor[InputType any, QueryFuncType core.QueryFunc] struct {
	queryer   *Queryer[InputType]
	queryFunc QueryFuncType
}

// Proceed is like [Proceed] but with the pre-configured queryer and query function.
// See [NewProcessor].
func (p *Processor[InputType, QueryFuncType]) Proceed(ctx context.Context, input *InputType, dest any) error {
	return Proceed(ctx, p.queryer, input, dest, p.queryFunc)
}

// NewProcessor build a queryer processor in order to execute the
// generated sql query with always the same querying function.
func NewProcessor[InputType any, QueryFuncType core.QueryFunc](q *Queryer[InputType], f QueryFuncType) *Processor[InputType, QueryFuncType] {
	p := new(Processor[InputType, QueryFuncType])
	p.queryer = q
	p.queryFunc = f

	return p
}

type Filter[InputType any] struct {
	whereFunc  WhereFuncType[InputType]
	orderFunc  OrderFuncType[InputType]
	limitFunc  LimitFuncType[InputType]
	offsetFunc OffsetFuncType[InputType]
}

type Queryer[InputType any] struct {
	queryFunc QueryFuncType[InputType]
	Filter[InputType]
	arg any
}

// WithQueryParserFunc set the function that provides the "SELECT … FROM …" part of the queryer.
func (q *Queryer[InputType]) WithQueryParserFunc(f QueryFuncType[InputType]) *Queryer[InputType] {
	q.queryFunc = f

	return q
}

// WithWhereFunc set the function that provide the "where" part of the queryer.
func (q *Queryer[InputType]) WithWhereFunc(f WhereFuncType[InputType]) *Queryer[InputType] {
	q.whereFunc = f

	return q
}

// WithOrderFunc set the function that provide the "order" part of the queryer.
func (q *Queryer[InputType]) WithOrderFunc(f OrderFuncType[InputType]) *Queryer[InputType] {
	q.orderFunc = f

	return q
}

// WithLimitFunc set the function that provide the "limit" part of the queryer.
func (q *Queryer[InputType]) WithLimitFunc(f LimitFuncType[InputType]) *Queryer[InputType] {
	q.limitFunc = f

	return q
}

// WithOffsetFunc set the function that provide the "offset" part of the queryer.
func (q *Queryer[InputType]) WithOffsetFunc(f OffsetFuncType[InputType]) *Queryer[InputType] {
	q.offsetFunc = f

	return q
}

// SetArg set the arg wich will be forwarded to the chosen sql queryer
// function when querying if arg(s) is needed.
// arg can be sql unsafe.
func (q *Queryer[InputType]) SetArg(arg any) *Queryer[InputType] {
	q.arg = arg

	return q
}

// Parse return the SQL generated by the queryer
func (q *Queryer[InputType]) Parse(input *InputType) (sql string, args []any, err error) {
	query, qArgs, err := q.queryFunc(input)
	if err != nil {
		return "", nil, err
	}

	where, wArgs, err := q.whereFunc(input)
	if err != nil {
		return "", nil, err
	}

	order, oArgs, err := q.orderFunc(input)
	if err != nil {
		return "", nil, err
	}

	limit, lArgs, err := q.limitFunc(input)
	if err != nil {
		return "", nil, err
	}

	offset, offArgs, err := q.offsetFunc(input)
	if err != nil {
		return "", nil, err
	}

	// Concatenate all arguments
	args = append(args, qArgs...)
	args = append(args, wArgs...)
	args = append(args, oArgs...)
	args = append(args, lArgs...)
	args = append(args, offArgs...)

	sql = fmt.Sprintf(sqlFormat, query, where, order, limit, offset)

	return sql, args, nil
}

// Proceed executes the queryer using specialized dao.QueryFunc like
// [dao.DBService.SelectContext], [dao..DBService.GetContext], [dao..DBService.NamedSelectContext] etc…
func Proceed[InputType any, QF core.QueryFunc](
	ctx context.Context, q *Queryer[InputType],
	input *InputType, dest any, queryFunc QF) error {
	sql, args, err := q.Parse(input)
	if err != nil {
		return err
	}

	arg := any(args)
	if q.arg != nil {
		if len(args) > 0 {
			return errors.New("Parse query functions return not nil arguments while SetArg was used")
		}
		arg = q.arg
	}

	switch f := any(queryFunc).(type) {
	case core.QueryFuncArg:
		return f(ctx, dest, sql, arg)
	case core.QueryFuncArgs:
		switch a := arg.(type) {
		case []any:
			return f(ctx, dest, sql, a...)
		case nil:
			return f(ctx, dest, sql)
		default:
			return errors.Errorf("function need []any, %T given", a)
		}
	}

	return errors.New("unpredictible error (wtf)")
}

func New[InputType any]() *Queryer[InputType] {
	q := Queryer[InputType]{}
	q.
		WithQueryParserFunc(DefaultQueryParser).
		WithWhereFunc(WhereTrueFunc).
		WithOrderFunc(NoOrderFunc).
		WithLimitFunc(NoLimitFunc).
		WithOffsetFunc(NoOffsetFunc)

	return &q
}
