// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package qevents

import (
	"errors"
	"fmt"
)

const (
	// FilterNameAll is a FilterName of type all.
	FilterNameAll FilterName = "all"
	// FilterNameNext is a FilterName of type next.
	FilterNameNext FilterName = "next"
	// FilterNamePrevious is a FilterName of type previous.
	FilterNamePrevious FilterName = "previous"
)

var ErrInvalidFilterName = errors.New("not a valid FilterName")

// FilterNameValues returns a list of the values for FilterName
func FilterNameValues() []FilterName {
	return []FilterName{
		FilterNameAll,
		FilterNameNext,
		FilterNamePrevious,
	}
}

// String implements the Stringer interface.
func (x FilterName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FilterName) IsValid() bool {
	_, err := ParseFilterName(string(x))
	return err == nil
}

var _FilterNameValue = map[string]FilterName{
	"all":      FilterNameAll,
	"next":     FilterNameNext,
	"previous": FilterNamePrevious,
}

// ParseFilterName attempts to convert a string to a FilterName.
func ParseFilterName(name string) (FilterName, error) {
	if x, ok := _FilterNameValue[name]; ok {
		return x, nil
	}
	return FilterName(""), fmt.Errorf("%s is %w", name, ErrInvalidFilterName)
}

// MarshalText implements the text marshaller method.
func (x FilterName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FilterName) UnmarshalText(text []byte) error {
	tmp, err := ParseFilterName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// LimitNameAll is a LimitName of type all.
	LimitNameAll LimitName = "all"
	// LimitName1 is a LimitName of type 1.
	LimitName1 LimitName = "1"
	// LimitName2 is a LimitName of type 2.
	LimitName2 LimitName = "2"
	// LimitName3 is a LimitName of type 3.
	LimitName3 LimitName = "3"
	// LimitName4 is a LimitName of type 4.
	LimitName4 LimitName = "4"
	// LimitName5 is a LimitName of type 5.
	LimitName5 LimitName = "5"
)

var ErrInvalidLimitName = errors.New("not a valid LimitName")

// LimitNameValues returns a list of the values for LimitName
func LimitNameValues() []LimitName {
	return []LimitName{
		LimitNameAll,
		LimitName1,
		LimitName2,
		LimitName3,
		LimitName4,
		LimitName5,
	}
}

// String implements the Stringer interface.
func (x LimitName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LimitName) IsValid() bool {
	_, err := ParseLimitName(string(x))
	return err == nil
}

var _LimitNameValue = map[string]LimitName{
	"all": LimitNameAll,
	"1":   LimitName1,
	"2":   LimitName2,
	"3":   LimitName3,
	"4":   LimitName4,
	"5":   LimitName5,
}

// ParseLimitName attempts to convert a string to a LimitName.
func ParseLimitName(name string) (LimitName, error) {
	if x, ok := _LimitNameValue[name]; ok {
		return x, nil
	}
	return LimitName(""), fmt.Errorf("%s is %w", name, ErrInvalidLimitName)
}

// MarshalText implements the text marshaller method.
func (x LimitName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *LimitName) UnmarshalText(text []byte) error {
	tmp, err := ParseLimitName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// OrderNameNone is a OrderName of type none.
	OrderNameNone OrderName = "none"
	// OrderNameLast is a OrderName of type last.
	OrderNameLast OrderName = "last"
)

var ErrInvalidOrderName = errors.New("not a valid OrderName")

// OrderNameValues returns a list of the values for OrderName
func OrderNameValues() []OrderName {
	return []OrderName{
		OrderNameNone,
		OrderNameLast,
	}
}

// String implements the Stringer interface.
func (x OrderName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OrderName) IsValid() bool {
	_, err := ParseOrderName(string(x))
	return err == nil
}

var _OrderNameValue = map[string]OrderName{
	"none": OrderNameNone,
	"last": OrderNameLast,
}

// ParseOrderName attempts to convert a string to a OrderName.
func ParseOrderName(name string) (OrderName, error) {
	if x, ok := _OrderNameValue[name]; ok {
		return x, nil
	}
	return OrderName(""), fmt.Errorf("%s is %w", name, ErrInvalidOrderName)
}

// MarshalText implements the text marshaller method.
func (x OrderName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *OrderName) UnmarshalText(text []byte) error {
	tmp, err := ParseOrderName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// TypeNameAll is a TypeName of type all.
	TypeNameAll TypeName = "all"
	// TypeNameVisio is a TypeName of type visio.
	TypeNameVisio TypeName = "visio"
	// TypeNameNotVisio is a TypeName of type notVisio.
	TypeNameNotVisio TypeName = "notVisio"
)

var ErrInvalidTypeName = errors.New("not a valid TypeName")

// TypeNameValues returns a list of the values for TypeName
func TypeNameValues() []TypeName {
	return []TypeName{
		TypeNameAll,
		TypeNameVisio,
		TypeNameNotVisio,
	}
}

// String implements the Stringer interface.
func (x TypeName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TypeName) IsValid() bool {
	_, err := ParseTypeName(string(x))
	return err == nil
}

var _TypeNameValue = map[string]TypeName{
	"all":      TypeNameAll,
	"visio":    TypeNameVisio,
	"notVisio": TypeNameNotVisio,
}

// ParseTypeName attempts to convert a string to a TypeName.
func ParseTypeName(name string) (TypeName, error) {
	if x, ok := _TypeNameValue[name]; ok {
		return x, nil
	}
	return TypeName(""), fmt.Errorf("%s is %w", name, ErrInvalidTypeName)
}

// MarshalText implements the text marshaller method.
func (x TypeName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TypeName) UnmarshalText(text []byte) error {
	tmp, err := ParseTypeName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
